Neos:
    Flow:
      http:
        chain:
          'postprocess':
            chain:
              'Flownative.OpenIdConnect.Client:setJwtCookie':
                'position': 'after setSessionCookie'
                component: 'Flownative\OpenIdConnect\Client\Http\SetJwtCookieComponent'
                componentOptions:
                  cookieName: 'flownative_oidc_jwt'
                  secureCookie: true
                  authenticationProviderName: 'Flownative.OpenIdConnect.Client:OidcProvider'
